/* config.h.  Generated by cmake from config.h.cmake */
/* Don't add anything new here!!! Use per-directory generated files. */

/* Define if you ogg/vorbis installed */
#cmakedefine HAVE_VORBIS ${OGGVORBIS_VERSION}

/* Define to 1 if you have the <machine/endian.h> header file. */
#cmakedefine HAVE_MACHINE_ENDIAN_H 1

/* Define to 1 if you have the <endian.h> header file. */
#cmakedefine HAVE_SYS_ENDIAN_H 1

/* Define to 1 if you have the <sys/endian.h> header file. */
#cmakedefine HAVE_ENDIAN_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#cmakedefine HAVE_UNISTD_H 1
